# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nazwisko')),
            ],
            options={
                'verbose_name': 'Kandydata',
                'verbose_name_plural': 'Kandydaci',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa gminy')),
                ('type', models.CharField(choices=[('city', 'miasto'), ('village', 'wies'), ('abroad', 'zagranica'), ('ship', 'statek')], max_length=7, verbose_name='Typ')),
                ('habitancy', models.IntegerField(verbose_name='Liczba mieszkancow')),
                ('privileged', models.IntegerField(verbose_name='Liczba uprawnionych')),
                ('given_forms', models.IntegerField(verbose_name='Liczba wydanych kart')),
                ('filled_forms', models.IntegerField(verbose_name='Liczba wypelnionych kart')),
                ('correctly_filled_forms', models.IntegerField(verbose_name='Liczba poprawnie wypelnionych kart')),
                ('candidate1_votes', models.IntegerField()),
                ('candidate2_votes', models.IntegerField()),
                ('candidate1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate1', to='wyniki.Candidate')),
                ('candidate2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate2', to='wyniki.Candidate')),
            ],
            options={
                'verbose_name': 'gmina',
                'verbose_name_plural': 'gminy',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('identifier', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Identyfikator')),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Województwa',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Province', verbose_name='Województwo'),
        ),
    ]
